Rational
autwk/CoolRepository pull request #1
Opened 2023-03-18 11:40 UTC by autwk

2023-03-19 16:44 UTC, tanyaamiheeva requested changes

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.cpp
> +  }
Отделить if снизу пустой строкой

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.cpp
> +}
1) Отделить все функции друг от друга пустыми строками
2) Отделить if пустой строкой снизу

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.cpp
> +  q_ /= gcd;
Отделить if пустой строкой сверху

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.cpp
> +}
1) Отделить все функции друг от друга пустыми строками
2) Отделить if пустой строкой снизу

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.cpp
> +}
Отделить все функции друг от друга пустыми строками

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.cpp
> +int32_t GCD(int32_t a, int32_t b) {
Зачем int32_t, если есть просто int? Заменить везде в обоих файлах на int

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.cpp
> +}
Отделить функции пустой строкой

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.cpp
> +}
1) Отделить все функции друг от друга пустыми строками
2) Отделить if пустой строкой снизу

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.cpp
> +}
1) Отделить все функции друг от друга пустыми строками
2) s, f - плохой нейминг, выше же использовался first, лучше заменить на first и second

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.cpp
> +Rational operator+(const Rational& first, const Rational& other) {
first и other - не очень удачный нейминг, лучше first и second или left и right

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.cpp
> +  bool p_minus = false, q_minus = false, slash = false;
Лучше переименовать (например, p_minus_flag), чтобы сделать более информативными

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.cpp
> +    if (temp == '/') {
Отделить if пустой строкой сверху

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.cpp
> +  }
Отделить цикл пустой строкой

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.cpp
> +  q = (q_minus) ? -q : q;
Отделить if пустой строкой

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.cpp
> +  }
val.SetNumerator(p) в любом случае происходит, зачем делать его внутри if?

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.h
> +  int32_t p_ = 0;
Аналогично - заменить на int везде

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.h
> +  void Reduce();
Reduce нужно сделать private

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.h
> + private:
Лучше сначала public-блок, затем private

2023-03-19 16:44 UTC, tanyaamiheeva commented on rational.h
> +std::istream& operator>>(std::istream& is, Rational& val);
Операторы лучше разбить на смысловые группы (внутри класса почти хорошо сделано, лучше еще геттеры-сеттеры отделить от последующих четырех) - например, операторы сравнения, операторы ввода-вывода и т.д.

2023-03-19 17:45 UTC, autwk commented on rational.h
> +  void Reduce();
а если использую reduce() при вводе >> ?

2023-03-19 19:40 UTC, tanyaamiheeva commented on rational.h
> +  void Reduce();
> а если использую reduce() при вводе >> ?

Это никак не мешает)

2023-03-20 06:12 UTC, autwk commented on rational.h
> +  void Reduce();
function "Rational::Reduce" (declared at line 34) is inaccessible

Тогда я не совсем понимаю, что происходит не так, когда я reduce делаю private

2023-03-20 08:51 UTC, tanyaamiheeva commented on rational.h
> +  void Reduce();
> function "Rational::Reduce" (declared at line 34) is inaccessible
> 
> Тогда я не совсем понимаю, что происходит не так, когда я reduce делаю private

Ты делаешь Reduce внутри каждого из сеттеров, зачем его вообще делать в операторе ввода еще раз?

2023-03-24 13:37 UTC, tanyaamiheeva approved these changes
Все окей, засчитано:)

2023-03-24 13:37 UTC, merged